# Generated by Django 4.2.2 on 2023-07-14 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photo/removebg/%Y/%m/%d/')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='watermarkremove',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/watermarked/%Y/%m/%d/'),
        ),
    ]
